apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  labels:
    app: nodejs-postgresql-persistent
    template: nodejs-postgresql-persistent
  name: postgresql
  namespace: cluster-validation-nodejs
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    name: postgresql