apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: blackbox-exporter
data:
  config.yaml: |-
    modules:
      http_2xx:
        prober: http
      http_post_2xx:
        prober: http
        http:
          method: POST
      tcp_connect:
        prober: tcp
