apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  ports:
  - name: 9115-9115
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: blackbox-exporter
  type: ClusterIP