apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nodejs-postgresql-persistent
    template: nodejs-postgresql-persistent
  name: postgresql
  namespace: cluster-validation-nodejs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi