apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nodejs-postgresql-persistent
    template: nodejs-postgresql-persistent
  name: nodejs-postgresql-persistent
  namespace: cluster-validation-nodejs
stringData:
  database-admin-password: aUHhl0bKSNTPvsJA
  database-password: AFsWoEdXUDSdNMHd
  database-user: userFVB