apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-cluster-validation-nodejs-ns.yaml
- 00-imagestream-nodejs-postgresql-persistent.yaml
- 00-imagestream-nodejs-ubi8.yaml
- 10-buildconfig-nodejs-postgresql-persistent.yaml
- 20-pvc-cluster-validation-nodejs.yaml
- 30-service-postgresql.yaml
- 31-service-nodejs-postgresql-persistent.yaml
- 40-route-nodejs-postgresql-persistent.yaml
- 50-secret-nodejs-postgresql-persistent-template.yaml
- 60-deploymentconfig-postgresql.yaml
- 61-deploymentconfig-nodejs-postgresql-persistent.yaml